name: music_label_manager_advanced
description: Advanced music label royalty and client revenue manager
publish_to: "none"
version: 2.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  file_picker: ^8.0.0
  excel: ^4.0.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
